oplus-fwk: patch missing method inside OplusUIFirstManager
java.lang.NoSuchMethodError: No virtual method setUxThreadValue(IILjava/lang/String;)V in class Lcom/oplus/uifirst/OplusUIFirstManager